const FETCH_IMEI_WHITELIST_OR_NOT = 'FETCH_IMEI_WHITELIST_OR_NOT';
const FETCH_IMEI_WHITELIST_OR_NOT_SUCCEEDED = 'FETCH_IMEI_WHITELIST_OR_NOT_SUCCEEDED';
const FETCH_IMEI_WHITELIST_OR_NOT_FAILED = 'FETCH_IMEI_WHITELIST_OR_NOT_FAILED';
const FETCH_DROP_DOWN = 'FETCH_DROP_DOWN';
const FETCH_DROP_DOWN_SUCCEEDED = 'FETCH_DROP_DOWN_SUCCEEDED';
const FETCH_DROP_DOWN_FAILED = 'FETCH_DROP_DOWN_FAILED';
const FETCH_LIVE_TRACKING = 'FETCH_LIVE_TRACKING';
const FETCH_LIVE_TRACKING_SUCCEEDED = 'FETCH_LIVE_TRACKING_SUCCEEDED';
const FETCH_LIVE_TRACKING_FAILED = 'FETCH_LIVE_TRACKING_FAILED';
const FETCH_TRACKER_ADDING = 'FETCH_TRACKER_ADDING';
const FETCH_TRACKER_ADDING_SUCCEEDED = 'FETCH_TRACKER_ADDING_SUCCEEDED';
const FETCH_TRACKER_ADDING_FAILED = 'FETCH_TRACKER_ADDING_FAILED';

export{
    FETCH_IMEI_WHITELIST_OR_NOT,
    FETCH_IMEI_WHITELIST_OR_NOT_SUCCEEDED,
    FETCH_IMEI_WHITELIST_OR_NOT_FAILED,
    FETCH_DROP_DOWN,
    FETCH_DROP_DOWN_SUCCEEDED,
    FETCH_DROP_DOWN_FAILED,
    FETCH_LIVE_TRACKING,
    FETCH_LIVE_TRACKING_SUCCEEDED,
    FETCH_LIVE_TRACKING_FAILED,
    FETCH_TRACKER_ADDING,
    FETCH_TRACKER_ADDING_SUCCEEDED,
    FETCH_TRACKER_ADDING_FAILED
}